from django.urls import path,include


from .views import *
app_name = 'crm'

urlpatterns = [
    path('', user_login),
    path('validate/user', validate_user),
    path('accounts/login/', user_login, name='user_login'),
    path('log_out/', user_logout, name='user_logout'),
    path('dash-test', adminCall, name='admin_page'),
    path('user/create', Usercreate, name='user_create'),
    path('sales/profile/', memberHome, name='member_dash'),
    path('sales/<str:name>/profile/', SalesProfile, name='member'),
    path('update/profile', update_profile, name='member_dash'),
    path('<str:email>/update/profile', update_profile, name='update_profile'),
    path('account/create', account_form, name='add_account'),
    path('feedback', feedback, name='feedback'),
    path('add/lead', lead_form, name='add_lead'),
    path('add/opportunity', opprtunity_form, name='add_opportunity'),
    path('add/contact', contact_form, name='add_account'),
    path('account/list', account_list, name='account_list'),
    path('customer/list', lead_list, name='lead_list'),
    path('customer/list/<str:name>', lead_list),
    path('customer/list/<int:id>', lead_list),
    path('opportunity/list', opportunity_list, name='opportunity_list'),
    path('opportunity/list/<str:name>', opportunity_list),
    path('contact/list', contact_list, name='contact_list'),
    path('contact/list/<str:name>', contact_list),
    path('document/create', document_create, name='document_create'),
    path('api/email/v1', email_list),
    path('email/send', email_send, name='email_send'),
    path('email/list', email_list, name='email_list'),
    path('case/add', case, name='case_add'),
    path('case/list', case_list, name='case_list'),
    path('case/list/<str:name>', case_list),
    path('case/status/<str:id>', case_status),
    #path('item/list', Item_list, name='item_list'),
    path('select/order', SelectOrder, name='select_order'),
    path('order/address', orderAddress, name='order_address'),
    path('order', Order1, name='order'),
    path('document/list', document_list, name='document_list'),
    path('member/detail/<str:username>', SalesPersonProfile, name='member_detail'),
    path('ordered/items', Order_total, name='ordered_items'),
    path('ordered/items/<str:id>', Order_total, name='ordered_items'),
    path('api/getMeetings/v1', meeting_list, name='meetings'),
    path('api/meeting/add', meetingpost),
    path('api/opportunity/v1', OpprtunityStages.as_view(), name="opportunity_api"),
    path('api/lead/v1',LeadsStages.as_view(), name="lead_api"),
    path('feedback/list', feedback_list),
    path('api/sales/person/lead/v1', Sales_Lead.as_view(),name='sales_lead'),
    path('upload',import_order),
    #path('upload/lead', import_lead)
    path('add/order',Order_place,name='add_order'),
    path('api/task/v1', task_list),
    path('sales/persons', Sales_persons),
    #path('admin/opportunity', example),
    path('edit/opportunity/<int:id>',change_opportunity, name='edit_opportunity'),
    path('edit/lead/<int:id>',edit_lead),
    path('opportunity/admin', admin_opportunity),
    path('customer/admin', admin_lead),
    path('contact/admin', admin_contact),
    path('case/admin', admin_case),
    path('document/admin', admin_document),
    path('payment/admin', admin_payment),
    path('payment/admin/<str:id>', admin_payment),
    path('user/payment/list', user_payment),
    path('user/payment/list/<str:id>', user_payment),
    path('add/payment', add_payment),
    path('user/add/payment', user_add_payment),
    path('pending/opportunities', pending_order),
    path('pending/orders/<str:id>', pending_order),
    path('order/confirmation',order_confirmation),
    path('order/confirmation/<str:id>',order_confirmation),
    path('api/customer/data',customer_data),
    path('api/customer/order',customer_order),
    path('add/product',add_product),
    path('api/target/add',target),
    path('api/task/add',taskpost),
    path('api/sales/task',salestask),
    path('api/salestask/list',salestask_list),
    path('api/visit/task',visittask_list),
    path('api/sales/report', sales_report),
    path('get/performa/amount',Amount),
    path('proforma_quotation/list',p_q_userlist),
    path('porforma_quotation/list',p_q_list),
    path('proforma/form',pro_form),
    path('proforma/form/<int:id>',pro_form),
    path('quotation/form',quo_form,name='add_quotation'),
    path('quotation/form/<int:id>',quo_form,name='add_quotation'),
    path('quotation/invoice/pdf/<int:id>',pdf_view),
    path('performa/invoice/pdf/<int:id>',pdf_view_performa),
    path('get/quotation',quotation_data),
    path('get/product',product_data),
    path('get/notification',order_notifications),
    path('dispatch/profile',Dispatch_Person),
    path('dispatch/profile/<str:id>',Dispatch_Person),
    path('product/brief', product_brief),
    path('sales/order/pdf/<int:id>', sales_pdf),
    path('pay/order/track',order_name),
    path('sample/items', sample_total),
    path('sample/items/<str:id>', sample_total),
   path('add/sample',sample_place,name='add_sample'),
   path('detail/order/<int:id>',order_information),
   path('detail/sample/<int:id>',sample_information),
   path('detail/quotation/<int:id>',quotation_information),
    path('detail/performa/<int:id>',performa_information),
    path('detail/order/information/<int:id>',order_confirmation_information),
    path('detail/performa/information/<int:id>',performa_admin_information),
    path('detail/sample/information/<int:id>',sample_admin_information),
    path('detail/quotation/information/<int:id>',quotation_admin_information),
    path('detail/dispatch/information/<int:id>',dispatch_order_information),
    path('detail/customer/information/<int:id>',lead_information),
    path('feedback/data',feedback_data),
    path('sample/feedback/data',all_sample),
    path('detail/feedback/information/<int:id>',feedback_information),
    path('mail/check', mail_check),

]