# Generated by Django 2.2.4 on 2019-09-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Base_amount',
            new_name='total_amount',
        ),
    ]
