# Generated by Django 2.2.4 on 2019-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190906_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
