# Generated by Django 2.2.4 on 2019-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categories10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_quantity10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='per_item_price10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
