# Generated by Django 2.2.4 on 2019-09-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_performa_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='igsst_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
