# Generated by Django 2.2.4 on 2019-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190907_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='igsst_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='performa',
            name='total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
