# Generated by Django 2.2.4 on 2019-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190907_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
