# Generated by Django 2.2.4 on 2019-09-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_performa_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o1', to='crm.Performa'),
        ),
    ]
