# Generated by Django 2.2.4 on 2019-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20190908_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
