# Generated by Django 2.2.4 on 2019-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190908_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='tentative_date',
            field=models.DateField(auto_now=True),
        ),
    ]
