# Generated by Django 2.2.4 on 2019-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190909_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performa',
            name='tentative_date',
            field=models.DateField(),
        ),
    ]
