# Generated by Django 2.2.4 on 2019-09-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20190913_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='categories10',
            new_name='packaging10',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories2',
            new_name='packaging2',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories3',
            new_name='packaging3',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories4',
            new_name='packaging4',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories5',
            new_name='packaging5',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories6',
            new_name='packaging6',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories7',
            new_name='packaging7',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories8',
            new_name='packaging8',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='categories9',
            new_name='packaging9',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity10',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity2',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity3',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity4',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity5',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity6',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity7',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity8',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='item_quantity9',
        ),
        migrations.AlterField(
            model_name='sample',
            name='packaging',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
