# Generated by Django 2.2.4 on 2019-09-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20190915_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='review',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfaction',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment10',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment5',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment6',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment7',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment8',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment9',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Lead'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample10_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample1_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample2_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample3_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample4_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample5_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample6_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample7_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample8_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample9_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample_letter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
