# Generated by Django 2.2.4 on 2019-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20190917_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
