# Generated by Django 2.2.4 on 2019-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_emailcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('email_host', models.CharField(max_length=1024, verbose_name='EMAIL_HOST')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='EMAIL_PORT')),
            ],
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='email',
            field=models.CharField(max_length=255, verbose_name='EMAIL_HOST_USER'),
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='password',
            field=models.CharField(max_length=255, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
    ]
