# Generated by Django 2.2.4 on 2019-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20190917_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_USER'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
    ]
