# Generated by Django 2.2.4 on 2019-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20190919_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='item_quantity4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
