# Generated by Django 2.2.4 on 2019-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20190919_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='gst_number',
            field=models.CharField(max_length=30),
        ),
    ]
